---
root_group: root
nginx_user: www-data
nginx_group: www-data
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_sites_enabled_path: /etc/nginx/sites-enabled
nginx_sites_available_path: /etc/nginx/sites-available
nginx_default_host: default
nginx_cache_path: /var/run/nginx-cache

nginx_conf_template: "nginx.conf.j2"
nginx_host_template: "host.conf.j2"

nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'