---
- name: Write swapfile
  ansible.builtin.command:
    cmd: fallocate -l {{ swapfile_size }} {{ swapfile_location }}
    creates: '{{ swapfile_location }}'
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  ansible.builtin.file:
    path: '{{ swapfile_location }}'
    mode: 0600
  when: swapfile_size != false

- name: Create swapfile
  ansible.builtin.command: mkswap {{ swapfile_location }}
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  become: true
  ansible.builtin.command: swapon {{ swapfile_location }}
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: '{{ swapfile_location }}  none   swap   sw   0   0'
    state: present
  when: swapfile_size != false

- name: Configure vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '{{ swapfile_swappiness | string }}'
    reload: true
    state: present
  when: swapfile_swappiness != false

- name: Configure vm.vfs_cache_pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: '{{ swapfile_vfs_cache_pressure | string }}'
    reload: true
    state: present
  when: swapfile_vfs_cache_pressure != false