---
- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Validate Nginx Configuration
  ansible.builtin.command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
