---
# Extra packages to install (in addition to distro-specific default lists).
php_packages_extra: []

# PHP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
php_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
php_install_recommends: true

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: true

php_install_composer: true

# PHP-FPM configuration.
php_enable_php_fpm: true
php_fpm_state: started
php_fpm_handler_state: restarted
php_fpm_enabled_on_boot: true
# https://raw.githubusercontent.com/pixelb/ps_mem/master/ps_mem.py
# process_memory = sudo python ps_mem.py | grep php-fpm
# pm_max_children = ( total memory - used memory ) / {process_memory}
# round up
php_fpm_pm_max_children: 25
# Number of CPU cores x 4
php_fpm_pm_start_servers: 8
# Number of CPU cores x 2
php_fpm_pm_min_spare_servers: 4
# Same as `php_fpm_pm_start_servers`
php_fpm_pm_max_spare_servers: 8
php_fpm_pm_process_idle_timeout: "6s"
php_fpm_pm_max_requests: 1000

# PHP-FPM pool configuration
php_fpm_pools:
  - pool_name: www
    pool_template: www.conf.j2
    pool_pm: dynamic
    pool_pm_max_children:  "{{ php_fpm_pm_max_children }}"
    pool_pm_start_servers: "{{ php_fpm_pm_start_servers }}"
    pool_pm_min_spare_servers: "{{ php_fpm_pm_min_spare_servers }}"
    pool_pm_max_spare_servers: "{{ php_fpm_pm_max_spare_servers }}"
    pool_pm_process_idle_timeout: "{{ php_fpm_pm_process_idle_timeout }}"
    pool_php_fpm_pm_max_requests: "{{ php_fpm_pm_max_requests }}"

# OpCache settings.
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "96"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "4096"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "2"
php_opcache_max_file_size: "0"
php_opcache_blacklist_filename: ""

# If this is set to false, none of the following options will have any effect.
# Any and all changes to /etc/php.ini will be your responsibility.
php_use_managed_ini: true

php_expose_php: "Off"
php_max_execution_time: "60"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "32K"

php_file_uploads: "On"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"

php_post_max_size: "64M"
php_allow_url_fopen: "On"
php_date_timezone: "UTC" # perhaps set this to brand region instead

php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_output_buffering: "4096"
php_short_open_tag: "Off"
php_disable_functions: []
php_precision: 14
php_serialize_precision: "-1"

php_session_save_handler: files
php_session_save_path: ''
php_session_cookie_lifetime: 0

php_session_gc_probability: 1
php_session_gc_divisor: 1000
php_session_gc_maxlifetime: 1440

php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"
